### ISSUE TITLE
Implement Challenge API Object

### ISSUE THREAD

**Issue by mohamed-rafraf** [kubeflag/kubeflag#2]
Define the Challenge Custom Resource Definition (CRD) with fields like Template! The user can define the template (Deployment Template) and Also the TTL and the exposed Container Name! 
An instance can be created based on this template. 

An example of the Challenge object

```yaml 
apiVersion: kubeflag.io/v1alpha1
kind: Challenge
metadata:
  name: web-1
spec:
  defaultTTL: 5m
  template:
    spec:
      containers:
        - image: nginx:alpine
          name: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 80
```
