### ISSUE TITLE
Implement ChallengeInstance API Object

### ISSUE THREAD

**Issue by mohamed-rafraf** [kubeflag/kubeflag#3]
Define the `ChallengeInstance` CRD that references the `Challenge` resource! 
In this ChallengeInstance we can define the Challenge Reference, the username, and the team! 

Basically a challenge instance will be created by a CTF player, so we need to track username and team (for future features like policies)

This is an example 

```yaml 
apiVersion: kubeflag.rafraf.io/v1alpha1
kind: ChallengeInstance
metadata:
  name: kill-me-now
spec:
  challengeRef: web-1
  user: mohamed
  team: soter14
  ttl: 2m
```
